version: '2'

services:
  cooperative:
    build: .
    container_name: cooperatives
    image: cooperatives
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=mysecretpassword
      - DATABASE_NAME=cooperatives
      - DATABASE_PORT=5432
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_MULTIPLE_DATABASES="cooperatives","keycloak"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
  keycloak:
    image: jboss/keycloak
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_ADDR=postgres
      - DB_PORT=5432
      #- DB_DATABASE=keycloak
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=keycloak